MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 2
  RESNETS:
    NORM: "FrozenBN" 
    OUT_FEATURES: ["res4"]
    DEPTH: 50
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 300
    ANCHOR_SIZES: (32, 64, 128, 256)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("dotagta_train",)
  TEST: ("dotagta_val",)
SOLVER:
  BASE_LR: 0.008
  STEPS: (50000,)
  MAX_ITER: 150000
  IMS_PER_BATCH: 8
  PATIENCE: 3

TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: "checkpoint/dotagta_source_v1"
DATALOADER:
  NUM_WORKERS: 16