MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 15
  RESNETS:
    DEPTH: 50
    NORM: "FrozenBN" 
    OUT_FEATURES: ["res4"]
INPUT:
  MIN_SIZE_TRAIN: (800, 900, 1000, 1100, 1200)
  MAX_SIZE_TRAIN: 1999
  MIN_SIZE_TEST: 1200
  MAX_SIZE_TEST: 1999
DATASETS:
  TRAIN: ("dota_train",)
  TEST: ("dota_val",)
SOLVER:
  BASE_LR: 0.01
  STEPS: (50000,)
  MAX_ITER: 70000
  IMS_PER_BATCH: 8
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "checkpoint/dota_source"
DATALOADER:
  NUM_WORKERS: 16