MODEL:
  META_ARCHITECTURE: "student_sfda_RCNN"
  WEIGHT: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 2
  RESNETS:
    NORM: "FrozenBN" 
    OUT_FEATURES: ["res4"]
    DEPTH: 50
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 300
    ANCHOR_SIZES: (32, 64, 128, 256)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("uavdtdota_train_daylight",)
  TEST: ("uavdtdota_val_daylight",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: () # not implemented
  IMS_PER_BATCH: 1
  WARMUP_ITERS: 0
SOURCE_FREE:
  TYPE: True
  MODE: True
  METHOD: "LPLD"
  KEEP_RATE: 0.8
  EMAPERIOD: 1000
DATALOADER:
  NUM_WORKERS: 16
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: "./checkpoints_sfda/dota2uavdt"